### ISSUE TITLE
Multimodal component stopped working

### ISSUE THREAD

**Issue by hector** [trompamusic/trompa-multimodal-component#32]
In the test api Multimodal component stopped working.

I attach an example of the requests it does:

```graphql
query($query: String!, $first: Int = 9999) {
  allResults: searchMetadataText(
    onTypes: [DigitalDocument]
    onFields: [title]
    substring: $query
    first: $first
  ) {
    ... on DigitalDocument {
      identifier
      name
      _searchScore
      __typename
    }
    __typename
  }
}
```
Variables:
```json
{
  "first": 9999,
  "query": ""
}
```

Response:
```json
{
  "errors": [
    {
      "message": "Cannot read property '_values' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allResults"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errors": [
            {
              "message": "Cannot read property '_values' of undefined",
              "locations": [],
              "path": [
                "searchMetadataText"
              ]
            }
          ],
          "stacktrace": [
            "Error: Cannot read property '_values' of undefined",
            "    at new CombinedError (/app/node_modules/graphql-tools/dist/stitching/errors.js:82:28)",
            "    at Object.checkResultAndHandleErrors (/app/node_modules/graphql-tools/dist/stitching/errors.js:98:15)",
            "    at CheckResultAndHandleErrors.transformResult (/app/node_modules/graphql-tools/dist/transforms/CheckResultAndHandleErrors.js:9:25)",
            "    at /app/node_modules/graphql-tools/dist/transforms/transforms.js:25:54",
            "    at Array.reduce (<anonymous>)",
            "    at applyResultTransforms (/app/node_modules/graphql-tools/dist/transforms/transforms.js:24:23)",
            "    at /app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:105:50",
            "    at step (/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:32:23)",
            "    at Object.next (/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:13:53)",
            "    at fulfilled (/app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:4:58)"
          ]
        }
      }
    }
  ],
  "data": {
    "allResults": null
  }
}
```

**Comment by ChristiaanScheermeijer** [comment]
Thanks for pointing this out. It was the result of this PR: https://github.com/trompamusic/ce-api/pull/122
